/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_mobile_analytics_app_id": "43ef8a6940d74a7a9fb572a1416c0a63",
    "aws_mobile_analytics_app_region": "us-east-2",
    "Analytics": {
        "AWSPinpoint": {
            "appId": "43ef8a6940d74a7a9fb572a1416c0a63",
            "region": "us-east-2"
        }
    },
    "aws_appsync_graphqlEndpoint": "https://b5hludfzxncyforwprxhoy3hsu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-bpwxnjj7qfe23jmgodjb44ndju",
    "aws_cognito_identity_pool_id": "us-east-2:f0326d36-9141-4fc0-9a22-57f7bcb47406",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_B0LmQoJXg",
    "aws_user_pools_web_client_id": "5shp787nnf0k1c0ej4r1epmlk8",
    "oauth": {
        "domain": "whiskeysocial1f41304e-1f41304e-prod.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "whiskeysocial://",
        "redirectSignOut": "whiskeysocial://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE",
        "APPLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "whiskeysocials3111430-prod",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
