/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_mobile_analytics_app_id": "b136bbfdd3924b7697201a1ff3f945a6",
    "aws_mobile_analytics_app_region": "us-east-2",
    "Analytics": {
        "AWSPinpoint": {
            "appId": "b136bbfdd3924b7697201a1ff3f945a6",
            "region": "us-east-2"
        }
    },
    "aws_appsync_graphqlEndpoint": "https://vxlixvxebza6harw6vj5zygkbq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-vtd4psjd55dm7fi6ig5ko76bzi",
    "aws_cognito_identity_pool_id": "us-east-2:862ede3f-2ab8-4084-9650-070440ae835d",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_7AMsBAhBE",
    "aws_user_pools_web_client_id": "34jhdknq1t33nlrbn4rgs28pv5",
    "oauth": {
        "domain": "whiskeysocial1f41304e-1f41304e-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "whiskeysocial://",
        "redirectSignOut": "whiskeysocial://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE",
        "APPLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "whiskeysocials3111547-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
